server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Precipitation?serverTimezone=GMT$2d7
    username: root
    password: 123456
